plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

kramdown:
  parse_block_html: false

exclude: ['vendor', 'setup.sh', 'jekyll.sh']
include:
  - _pages

timezone: America/Los_Angeles

url: https://ucsb-cs16.github.io
baseurl: "/f21"
github_url: https://github.com/ucsb-cs16/f21

title: "UCSB CS16"
course: "CS16"
qtr: "F21"
quarter: "Fall 2021"

ta_names: "April,Ashley,Avishek,Kevin,Lucas,Nawel,Satyam,and Shu"
la_names: "Arthur,Connor,and Jerry"
la_apprentice_names: "Cameron and Sydney"
lab_times: "W: 1p,2p,3p,4p,5p,6p,7p,8p"
instructor: "Phill Conrad"
lecture_times: "TR - 2:00p-3:15p"
lecture_location: "CHEM 1179"
github_org: ucsb-cs16-f21

gauchospace: https://gauchospace.ucsb.edu
campuswire: https://campuswire.com/c/G931DC7FE/feed

start_week: 0
start_date: 2021-09-19 
num_weeks: 11
extra_exam_week: true
lecture_days_of_week: TR

instructor_url: https://ucsb-cs16.github.io/instructor

cal_dates: >
  [                                                                            
    {"label":"F21 1st day of instruction", "date":"2021-09-23" },
    {"label":"Veterans' Day", "date":"2021-11-11" },
    {"label":"Thanksgiving", "date":"2021-11-25" },
    {"label":"Thanksgiving", "date":"2021-11-26" },
    {"label":"F21 instruction ends", "date":"2021-12-03" },
    {"label":"F21 finals start", "date":"2021-12-04" },
    {"label":"F21 CS16 MIDTERM (2pm-3:15pm)", "date":"2021-10-28" },                      
    {"label":"F21 CS16 FINAL (4pm-7pm)", "date":"2021-12-07" },                      
    {"label":"F21 finals end", "date":"2021-12-10" },                          
    {"label":"F21 qtr ends", "date":"2021-12-10" }                              
  ]


collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
